query RunInput {
  shop {
    metafield(namespace: "discounts-allocator", key: "function-configuration") {
      value
    }
  }
  cart {
    lines {
      quantity
      cost {
        totalAmount {
          amount
        }
      }
      discountAllocations {
        discountedAmount {
          amount
        }
      }
      merchandise {
        ... on ProductVariant {
          id
        }
      }
    }
    cost {
      subtotalAmount {
        amount
      }
      totalAmount {
        amount
        currencyCode
      }
    }
  }
}
