api_version = "unstable"

[[extensions]]
name = "discounts-combined"
handle = "discounts-combined"
uid = "fa26cfa9-fe0d-4e02-bb90-18847976e28b386d675d"
type = "function"


  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
