api_version = "unstable"

[[extensions]]
name = "t:name"
handle = "discounts-product"
type = "function"
uid = "46f8b751-0dfd-0f4f-6972-a9f6330bd7492a6b791d-1e4d-5e8d-8d8d-7d7d7d7d7d7d"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
